import React from "react";
import { createRoot } from "react-dom/client";
import { Activity, AlertTriangle, ArrowLeft, BarChart3, Bitcoin, Bot, CircleDot, Fish, Orbit, Radio, Search, ShieldCheck, Waves } from "lucide-react";
import "./styles.css";

const coinMeta = { BRTI: { name: "Bitcoin", symbol: "BTC", accent: "#f7b955" }, SOLUSD_RTI: { name: "Solana", symbol: "SOL", accent: "#59d6d0" } };
const tabs = { active: "/api/active", closed: "/api/closed?limit=200", shadow: "/api/shadow-active" };
function money(value) { return value == null || Number.isNaN(Number(value)) ? "--" : `$${Number(value).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function percent(value) { return value == null ? "--" : `${(Number(value) * 100).toFixed(1)}%`; }
function metaFor(indexId) { return coinMeta[indexId] || { name: indexId || "Unknown", symbol: indexId || "--", accent: "#a8b4c7" }; }
function MarketIcon({ indexId, size = 21 }) { if (indexId === "BRTI") return <Bitcoin size={size} strokeWidth={2.2} />; if (indexId === "SOLUSD_RTI") return <Orbit size={size} strokeWidth={2.2} />; return <CircleDot size={size} />; }
function countdown(ms) { const seconds = Math.max(0, Math.floor(ms / 1000)); return `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }

function Review({ market }) {
  const reviews = [["6:30 review", market.llm_early_decision, market.llm_early_reason], ["2:30 review", market.llm_late_decision, market.llm_late_reason]].filter(([, decision]) => decision);
  if (!reviews.length) return null;
  return <section className="review" aria-label="Jetson LLM risk review"><div className="review-title"><Bot size={16} /> JETSON REVIEW</div>{reviews.map(([stage, decision, reason]) => <div className={`review-row review-${decision.toLowerCase()}`} key={stage}><span>{stage}</span><strong>{decision.replace("_", " ")}</strong><small>{reason || "No explanation returned."}</small></div>)}</section>;
}

function Checks({ market }) {
  if (!market.decision_confirmation_detail) return null;
  let checks = [];
  try { checks = JSON.parse(market.decision_confirmation_detail); } catch { return null; }
  return <div className="checks">{checks.map((check) => <span className={check.agree ? "check pass" : "check"} key={check.name}><CircleDot size={12} />{check.name}</span>)}</div>;
}

function Outcome({ market }) {
  if (market.result !== "yes" && market.result !== "no" || market.decision_recommendation == null) return null;
  const predictedAbove = market.decision_recommendation === "BUY_YES";
  const settledAbove = market.result === "yes";
  const correct = predictedAbove === settledAbove;
  return <div className={`outcome ${correct ? "outcome-win" : "outcome-loss"}`}><strong>{correct ? "OUTCOME: WIN" : "OUTCOME: MISSED"}</strong><span>Settled {settledAbove ? "ABOVE" : "BELOW"} GOAL · Model predicted {predictedAbove ? "ABOVE" : "BELOW"}</span></div>;
}

function LiveGraph({ history, strike }) {
  const points = history || [];
  if (points.length < 2) return <div className="graph graph-empty"><span>Gathering live 10-minute tick history...</span></div>;
  const values = points.map((point) => Number(point.value));
  const min = Math.min(...values, Number(strike));
  const max = Math.max(...values, Number(strike));
  const range = max - min || 1;
  const coords = values.map((value, index) => `${(index / (values.length - 1)) * 100},${96 - ((value - min) / range) * 82}`).join(" ");
  const strikeY = 96 - ((Number(strike) - min) / range) * 82;
  const rising = values[values.length - 1] >= Number(strike);
  return <div className="graph"><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Live ten-minute price graph"><line className="graph-grid" x1="0" x2="100" y1="20" y2="20" /><line className="graph-grid" x1="0" x2="100" y1="55" y2="55" /><line className="graph-grid" x1="0" x2="100" y1="90" y2="90" /><line className="graph-strike" x1="0" x2="100" y1={strikeY} y2={strikeY} /><polyline className={rising ? "graph-line graph-up" : "graph-line graph-down"} points={coords} /></svg><div className="graph-label graph-low">LOW {money(min)}</div><div className="graph-label graph-goal">GOAL {money(strike)}</div><div className="graph-label graph-high">HIGH {money(max)}</div><span className="graph-caption">LIVE 10-MINUTE PRICE HISTORY</span></div>;
}

function WhalePanel({ ticker, onClose }) {
  const [minimum, setMinimum] = React.useState(() => Number(localStorage.getItem("whaleMinUsd")) || 100);
  const [customMinimum, setCustomMinimum] = React.useState(String(minimum));
  const [trades, setTrades] = React.useState([]);
  const [loading, setLoading] = React.useState(true);
  const load = React.useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/whale-trades?ticker=${encodeURIComponent(ticker)}&limit=30&min_usd=${minimum}`); setTrades(response.ok ? await response.json() : []); } catch { setTrades([]); } finally { setLoading(false); } }, [ticker, minimum]);
  React.useEffect(() => { load(); }, [load]);
  const chooseMinimum = (value) => { setMinimum(value); setCustomMinimum(String(value)); localStorage.setItem("whaleMinUsd", String(value)); };
  return <div className="whale-panel"><div className="whale-panel-head"><div><span className="eyebrow"><Fish size={14} /> ORDER FLOW</span><strong>Anonymous large fills</strong></div><button type="button" className="return-btn" onClick={(event) => { event.preventDefault(); event.stopPropagation(); onClose(); }}><ArrowLeft size={14} /> BACK TO SIGNAL</button></div><div className="whale-controls">{[0, 50, 100, 250, 500, 1000].map((value) => <button type="button" className={minimum === value ? "selected" : ""} key={value} onClick={() => chooseMinimum(value)}>{value ? `$${value}+` : "ALL"}</button>)}<form onSubmit={(event) => { event.preventDefault(); const value = Math.max(0, Number(customMinimum) || 0); chooseMinimum(value); }}><span>$</span><input type="number" min="0" step="10" value={customMinimum} onChange={(event) => setCustomMinimum(event.target.value)} aria-label="Custom minimum whale trade amount" /><button type="submit">APPLY</button></form></div>{loading ? <div className="whale-empty">Scanning order-book fills...</div> : trades.length ? <div className="whale-list">{trades.map((trade) => <div className="whale-row" key={`${trade.trade_id}-${trade.ts_ms}`}><span className={trade.side === "yes" ? "side-yes" : "side-no"}>{trade.side === "yes" ? "YES / UP" : "NO / DOWN"}</span><strong>{money(trade.notional_usd)}</strong><span>@ {Number(trade.price_cents || 0).toFixed(1)}c</span><small>{new Date(trade.ts_ms).toLocaleTimeString()}</small></div>)}</div> : <div className="whale-empty">No fills at or above {money(minimum)}.</div>}</div>;
}

function MarketCard({ market, livePrices, histories, now, decisionLeadSec, closed = false }) {
  const meta = metaFor(market.index_id);
  const [whalesOpen, setWhalesOpen] = React.useState(false);
  const currentPrice = livePrices[market.index_id] ?? market.index_price;
  const recommendation = market.decision_recommendation || "PENDING";
  const liveRecommendation = market.recommendation || "NO_EDGE";
  const direction = recommendation === "BUY_YES" ? "BET UP" : recommendation === "BUY_NO" ? "BET DOWN" : recommendation === "NO_EDGE" ? "NO TRADE" : "LOCKING IN";
  const liveBias = liveRecommendation === "BUY_YES" ? `Leaning UP (+${Math.abs(Number(market.edge || 0) * 100).toFixed(1)}% pricing edge)` : liveRecommendation === "BUY_NO" ? `Leaning DOWN (+${Math.abs(Number(market.edge || 0) * 100).toFixed(1)}% pricing edge)` : "No trade (fairly priced by market)";
  const gap = currentPrice == null ? null : Number(currentPrice) - Number(market.strike);
  const decisionAt = Number(market.close_ts_ms) - decisionLeadSec * 1000;
  const remaining = Number(market.close_ts_ms) - now;
  const decisionRemaining = decisionAt - now;
  const lockedModel = market.decision_model_p_yes ?? market.model_p_yes;
  const lockedEdge = market.decision_edge ?? market.edge;
  return <article className={`market-card ${closed ? "market-closed" : ""}`} style={{ "--accent": meta.accent }}><header className="market-header"><div className="coin-mark"><MarketIcon indexId={market.index_id} /></div><div><h2>{meta.name} <em>15m</em></h2><code>{market.ticker}</code></div><div className="market-time"><Radio size={14} /> {closed ? "CLOSED" : "LIVE"}<strong>{closed ? "SETTLED" : countdown(remaining)}</strong></div></header>{whalesOpen ? <WhalePanel ticker={market.ticker} onClose={() => setWhalesOpen(false)} /> : <><div className={`signal signal-${recommendation.toLowerCase()}`}><span className="signal-kicker">{closed ? "SETTLED DECISION" : recommendation === "PENDING" ? "FINAL CALL LOCKS IN AT T-6:30" : "OFFICIAL SIGNAL"}</span><strong>{direction}</strong><span>{recommendation === "PENDING" ? `Live bias: ${liveBias}` : `${percent(market.decision_confidence)} confidence`}</span><b className="lock-timer">{recommendation === "PENDING" ? `LOCKS IN ${countdown(decisionRemaining)}` : `CLOSES IN ${countdown(remaining)}`}</b></div><div className="card-actions"><button type="button" onClick={() => setWhalesOpen(true)}><Fish size={14} /> WHALE TRACKER</button>{market.result && <span className={market.result === "yes" ? "result-yes" : "result-no"}>RESULT: {market.result.toUpperCase()}</span>}</div><Outcome market={market} /><Checks market={market} /><Review market={market} />{recommendation !== "PENDING" && <div className="decision-metrics"><div><label>LOCKED EDGE</label><strong>{lockedEdge == null ? "--" : `${lockedEdge >= 0 ? "+" : ""}${(Number(lockedEdge) * 100).toFixed(1)} pts`}</strong></div><div><label>WIN PROB</label><strong>{recommendation === "BUY_NO" ? percent(1 - lockedModel) : percent(lockedModel)}</strong></div><div><label>LOCKED PRICE</label><strong>{money(market.decision_index_price)}</strong></div></div>}<div className="price-grid"><div><label>LIVE INDEX</label><strong>{money(currentPrice)}</strong></div><div><label>GOAL PRICE</label><strong>{money(market.strike)}</strong></div><div><label>GAP TO GOAL</label><strong className={gap >= 0 ? "positive" : "negative"}>{gap == null ? "--" : `${gap >= 0 ? "+" : ""}${money(gap)}`}</strong></div></div><LiveGraph history={histories[market.index_id]} strike={market.strike} /><footer><span>Model {percent(market.model_p_yes)} above</span><span>Market {percent(market.market_p_yes)}</span><span>Checks {market.decision_confirmation_agree ?? "--"}/{market.decision_confirmation_total ?? "--"}</span></footer></>}</article>;
}

function ShadowCard({ market, livePrices }) { const meta = metaFor(market.index_id); return <article className="market-card shadow-card" style={{ "--accent": meta.accent }}><header className="market-header"><div className="coin-mark"><MarketIcon indexId={market.index_id} /></div><div><h2>{meta.name} <em>SHADOW</em></h2><code>{market.ticker}</code></div><div className="market-time"><BarChart3 size={14} /> EXPERIMENT</div></header><div className="signal signal-shadow"><span className="signal-kicker">REGULARIZED CHALLENGER</span><strong>{market.recommendation || "PENDING"}</strong><span>{percent(market.model_p_yes)} model probability</span></div><div className="price-grid"><div><label>INDEX</label><strong>{money(livePrices[market.index_id] ?? market.index_price)}</strong></div><div><label>GOAL</label><strong>{money(market.strike)}</strong></div><div><label>CONFIRMATION</label><strong>{market.confirmation_agree ?? "--"}/{market.confirmation_total ?? "--"}</strong></div></div></article>; }

function Hud({ calibration, external }) { const cards = [["Overall Engine", "ALL", calibration], ["Bitcoin Model", "BTC", calibration?.BRTI], ["Solana Model", "SOL", calibration?.SOLUSD_RTI]]; return <section className="hud"><div className="hud-head"><div><span className="eyebrow"><BarChart3 size={14} /> PERFORMANCE & CALIBRATION</span><h2>Accuracy telemetry</h2></div><span className={`feed-status ${external?.healthy ? "healthy" : "stale"}`}><Radio size={13} /> {external?.healthy ? "EXTERNAL FEED LIVE" : "EXTERNAL FEED STALE"}</span></div><div className="hud-grid">{cards.map(([title, symbol, card]) => <div className="hud-card" key={title}><div className="hud-card-top"><span>{symbol}</span><strong>{title}</strong></div>{card?.n ? <div className="hud-values"><div><label>MODEL BRIER</label><b>{Number(card.model_brier).toFixed(3)}</b></div><div><label>MARKET BRIER</label><b>{Number(card.market_brier).toFixed(3)}</b></div><div><label>SETTLED</label><b>{card.n}</b></div></div> : <div className="hud-empty">Collecting calibration data...</div>}</div>)}</div></section>; }

function ShadowComparison({ data }) { if (!data?.groups?.length) return <div className="shadow-empty">Shadow models are waiting for the first locked decision.</div>; return <div className="shadow-comparison">{data.groups.map((group) => { const live = group.scores?.live || {}; const shadow = group.scores?.shadow || {}; const market = group.scores?.market || {}; const better = shadow.n > 0 && shadow.brier < live.brier; return <div className={`shadow-compare-card ${better ? "better" : ""}`} key={group.index_id}><div className="shadow-compare-head"><strong>{metaFor(group.index_id).name}</strong><span>{better ? "BETTER THAN LIVE" : "COLLECTING EVIDENCE"}</span></div><div className="shadow-compare-values"><div><label>LIVE BRIER</label><b>{live.brier == null ? "--" : Number(live.brier).toFixed(3)}</b></div><div><label>CANDIDATE BRIER</label><b>{shadow.brier == null ? "--" : Number(shadow.brier).toFixed(3)}</b></div><div><label>MARKET BRIER</label><b>{market.brier == null ? "--" : Number(market.brier).toFixed(3)}</b></div></div><small>{shadow.n || 0} settled · {group.pending || 0} pending · {shadow.actionable_correct || 0}/{shadow.actionable_n || 0} candidate calls correct</small></div>; })}</div>; }

function App() {
  const [tab, setTab] = React.useState("active"); const [coin, setCoin] = React.useState("all"); const [query, setQuery] = React.useState(""); const [rows, setRows] = React.useState([]); const [livePrices, setLivePrices] = React.useState({}); const [histories, setHistories] = React.useState({}); const [calibration, setCalibration] = React.useState(null); const [external, setExternal] = React.useState(null); const [shadowComparison, setShadowComparison] = React.useState(null); const [status, setStatus] = React.useState("CONNECTING"); const [lastUpdated, setLastUpdated] = React.useState(null); const [now, setNow] = React.useState(Date.now()); const [decisionLeadSec, setDecisionLeadSec] = React.useState(390);
  const load = React.useCallback(async () => { try { const response = await fetch(tabs[tab], { cache: "no-store" }); if (!response.ok) throw new Error(); const nextRows = await response.json(); setRows(nextRows); setStatus("LIVE"); setLastUpdated(new Date()); const ids = [...new Set(nextRows.map((row) => row.index_id).filter(Boolean))]; const seeded = await Promise.all(ids.map(async (id) => { try { const result = await fetch(`/api/price-history?index_id=${encodeURIComponent(id)}&minutes=10`); return [id, result.ok ? await result.json() : []]; } catch { return [id, []]; } })); setHistories((old) => ({ ...old, ...Object.fromEntries(seeded) })); } catch { setStatus("API OFFLINE"); } }, [tab]);
  React.useEffect(() => { load(); const interval = setInterval(load, tab === "shadow" ? 30000 : 5000); return () => clearInterval(interval); }, [load, tab]);
  React.useEffect(() => { fetch("/api/config").then((response) => response.json()).then((config) => setDecisionLeadSec(Number(config.decision_lead_sec) || 390)).catch(() => {}); Promise.all([fetch("/api/calibration").then((r) => r.json()), fetch("/api/calibration?index_id=BRTI").then((r) => r.json()), fetch("/api/calibration?index_id=SOLUSD_RTI").then((r) => r.json())]).then(([all, btc, sol]) => setCalibration({ ...all, BRTI: btc, SOLUSD_RTI: sol })).catch(() => {}); const interval = setInterval(() => fetch("/api/external-status").then((r) => r.json()).then(setExternal).catch(() => {}), 5000); return () => clearInterval(interval); }, []);
  React.useEffect(() => { if (tab !== "shadow") return undefined; const loadComparison = () => fetch("/api/shadow-comparison?limit=10000", { cache: "no-store" }).then((response) => response.json()).then(setShadowComparison).catch(() => setShadowComparison(null)); loadComparison(); const interval = setInterval(loadComparison, 30000); return () => clearInterval(interval); }, [tab]);
  React.useEffect(() => { const interval = setInterval(() => setNow(Date.now()), 1000); let socket; let retryTimer; let retryMs = 1000; let stopped = false; const connect = () => { if (stopped) return; socket = new WebSocket(`${location.protocol === "https:" ? "wss" : "ws"}://${location.host}/ws/live`); socket.onmessage = (event) => { try { const message = JSON.parse(event.data); if (message.type === "index_tick") { setLivePrices((old) => ({ ...old, [message.index_id]: message.value })); setHistories((old) => ({ ...old, [message.index_id]: [...(old[message.index_id] || []), { ts_ms: message.ts_ms, value: message.value }].slice(-600) })); } } catch {} }; socket.onopen = () => { retryMs = 1000; setStatus("LIVE"); }; socket.onerror = () => { setStatus("API OFFLINE"); socket.close(); }; socket.onclose = () => { if (!stopped) { setStatus("CONNECTING"); retryTimer = setTimeout(connect, retryMs); retryMs = Math.min(retryMs * 2, 15000); } }; }; connect(); return () => { stopped = true; clearInterval(interval); clearTimeout(retryTimer); socket?.close(); }; }, []);
  const filtered = rows.filter((row) => (coin === "all" || row.index_id === coin) && (!query || [row.ticker, row.index_id, row.strike].some((value) => String(value || "").toLowerCase().includes(query.toLowerCase()))));
  return <main className="shell"><header className="topbar"><div className="brand"><span className="brand-mark">AQ</span><div><strong>AQLABS</strong><small>QUANTITATIVE CRYPTO ENGINE</small></div></div><div className="status"><span className={status === "LIVE" ? "status-dot live" : "status-dot"}></span>{status}<span className="updated">{lastUpdated ? lastUpdated.toLocaleTimeString() : "--"}</span></div></header><section className="intro"><div><p className="eyebrow"><Activity size={15} /> MARKET MONITOR</p><h1>15-minute signal intelligence</h1><p className="lede">Prediction, calibration, order flow, live graph, and Jetson risk review in one surface.</p></div><div className="monitor"><ShieldCheck size={19} /> READ-ONLY MONITOR MODE</div></section><Hud calibration={calibration} external={external} />{status === "API OFFLINE" && <div className="alert"><AlertTriangle size={17} /> Python API is unavailable. Retrying automatically.</div>}<nav className="toolbar"><div className="tabs">{[["active", "Active Markets"], ["closed", "Closed History"], ["shadow", "Shadow Lab"]].map(([key, label]) => <button className={tab === key ? "active" : ""} key={key} onClick={() => setTab(key)}>{label}<b>{tab === key ? rows.length : ""}</b></button>)}</div><div className="filters"><button className={coin === "all" ? "active" : ""} onClick={() => setCoin("all")}>ALL</button><button className={coin === "BRTI" ? "active" : ""} onClick={() => setCoin("BRTI")}>BTC</button><button className={coin === "SOLUSD_RTI" ? "active" : ""} onClick={() => setCoin("SOLUSD_RTI")}>SOL</button><label><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter ticker or goal" /></label></div></nav>{tab === "shadow" && <ShadowComparison data={shadowComparison} />}<section className="section-heading"><div><span className="eyebrow"><Waves size={15} /> {tab.toUpperCase()} FEED</span><h2>{filtered.length} {tab === "active" ? "active markets" : tab === "closed" ? "closed markets" : "shadow forecasts"}</h2></div><span className="polling">Updated {lastUpdated ? lastUpdated.toLocaleTimeString() : "--"}</span></section><section className="markets">{filtered.length ? filtered.map((market) => tab === "shadow" ? <ShadowCard market={market} livePrices={livePrices} key={market.ticker} /> : <MarketCard market={market} livePrices={livePrices} histories={histories} now={now} decisionLeadSec={decisionLeadSec} closed={tab === "closed"} key={market.ticker} />) : <div className="empty">No markets match the current view.</div>}</section></main>;
}

createRoot(document.getElementById("root")).render(<App />);
